version: '3'
services:
  practice_jpa:
    profiles:
      - "local"
    platform: linux/x86_64
    container_name: mysql8_jpa
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: jpa
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "${HOST_PORT:-3312}:3306"
    volumes:
      - ./local-db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql