server:
  port: 8080
  servlet:
    context-path: /jpa
spring:
  application:
    name: jpa
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3312/jpa
