###

GET http://localhost:8080/jpa/user/{{id}}

###

POST http://localhost:8080/jpa/user
Content-Type: application/json

{
  "name" : "VK",
  "address": "Canada"
}

###

GET http://localhost:8080/jpa/categories

###

GET http://localhost:8080/jpa/categories?id=1

###

GET http://localhost:8080/jpa/categories?id=4&name=Books
